Better runner compatibility with testnet
Agoric/testnet-load-generator pull request #44
Opened 2022-01-08 08:26 UTC by mhofman

This PR updates the runner with a grab bag of fixes I did while making the stats generation more robust, and working on moving the provisioning check of the client for a testnet chain to the setup phase.

Checking earlier allows the testnet loadgen to pause before starting and wait until the client is provisioned, instead of requiring action after the start, which may be a while when catching up to an existing chain. I originally started adding the ability to auto provision a client for a local testnet (based on the keys and the same logic as a local-chain), but reverted course and moved that functionality into a separate script used by the integration test (see https://github.com/Agoric/agoric-sdk/pull/4256).

List of various fixes:
- Update to node 16 and Debian bullseye (with fallback to node 14 for older incompatible SDKs)
- Handle some older SDK versions which output lockdown sniffing to stdout instead of stderr
- Rewrote the config argv parsing logic, to make it behave slightly more sanely
- Fixed some deadlock issues, e.g. adding some timeouts on task ready (see #40) or slog streams not closing properly
- Capture client storage and slog file (should help track some transient seg faults in the solo)
- Automatically capture the state of the client and chain if an error occurs (see #39)
- Background the compression of the state directories after snapshotting them (overlayfs supports CoW). Closes #39 
- Avoid resetting the whole `agoric-servers` project in `local-chain` tests. Removes loadgen project `git` dependency.
- Elide long lines from the chain or solo output (improves github actions perf, see https://github.com/Agoric/agoric-sdk/pull/4113)

2022-01-09 22:46 UTC, michaelfig approved these changes
LGTM!

The only stylistic issue I have is that you're using `... == null` and `... != null`, which the team has vowed never to do (except as an accident).  I can understand that maybe it's a terse way to express what you want, but I would be more comfortable if you wrote things out explicitly using `===` or `!==`.  I can't really tell what your intent is with the double-equals forms.

2022-01-09 23:04 UTC, mhofman commented
> The only stylistic issue I have is that you're using `... == null` and `... != null`, which the team has vowed never to do

Interesting. If that's the case we probably should have the corresponding eslint rule enabled.

I've been following the `== null` rule to mean null-ish, so either `null` or `undefined`, which the community seem to have settled on, including by standardizing `?.` and `??`.

2022-01-09 23:17 UTC, michaelfig commented
> Interesting. If that's the case we probably should have the corresponding eslint rule enabled.

Even more interesting, the "require triple-equals" rule has exceptions for `== null`.

> I've been following the `== null` rule to mean null-ish, so either `null` or `undefined`, which the community seem to have settled on, including by standardizing `?.` and `??`.

That's a good enough reason for me.  I don't want to block landing this change, but I do want to be sure @erights is aware of these deviations from Jessie:

For context, this is the `loadgen` package, which definitely is bound to Node.js, and is running off-chain.  It may be a good reason to allow deviations from Jessie where they are community-accepted idioms (including using the `class` keyword, which some of our code seems to need to do to interact with external libraries).

2022-01-09 23:23 UTC, mhofman commented
Oh yeah this is definitely node specific code. And I know I don't always strictly follow ocap for threading powers.

I also wasn't able to be strict about nested await. Might be interesting to do a pass later to see what could be done about all those deviations, but I'd rather not block these PR on that.

2022-01-10 01:46 UTC, erights commented
Where are these `== null` occurrences?

2022-01-10 02:24 UTC, michaelfig commented
> Where are these `== null` occurrences?

For example, https://github.com/Agoric/testnet-load-generator/pull/44/files#diff-01ae6218516e017b56a165545f3fa9bf13ae8abb57449c9ffaf49b7dbd048b48R650

2022-01-10 03:01 UTC, erights requested changes

2022-01-10 03:01 UTC, erights commented on runner/lib/main.js
> +                  cycleStats.duration != null &&
I don't think it is worth it. Please expand to test both `null` and `undefined` if that's the semantics you want. My reasoning:

Experienced JS and Node programmers will know the idiom. To any readers both unfamiliar with the idiom and with JS's truly bizarre `==` coercion rules, this is a barrier to understanding. One of my favorite Carl Hewitt quotes:

   ***A program should not only work, it should appear to work***

This code does not say what it means. Code should be read more often than it is written. The expertise required to read a piece of code and basically puzzle it out should be less than the expertise needed to write that code.

If you did want to keep the idiom, I'd say you must annotate each occurrence with an explanatory comment, which kinda defeats the purpose.

2022-01-10 03:02 UTC, erights commented on runner/lib/main.js
> +                  cycleStats.duration != null &&
Thanks for bringing this to my attention.

2022-01-17 17:30 UTC, warner approved these changes
If it works, I'm happy with it :)

2022-01-17 22:29 UTC, mhofman commented
@erights I'd like to merge this PR as-is. This is in the loadgen runner, and orchestrator cli, which is probably the furthest away from the chain you can get.

If disallowing `== null` is what we decide, I'd like this to be enforced by our `eslint` config, which this repo and package use.

2022-01-17 22:38 UTC, merged