Refactor loadgen to handle IST
Agoric/testnet-load-generator pull request #80
Opened 2022-05-13 00:25 UTC by mhofman

https://github.com/Agoric/agoric-sdk/pull/5332 is renaming RUN -> IST. This PR refactors the loadgen to no longer hardcode `run`, and instead names anything related with "stable". Then it adds a dynamic fallback from IST to RUN for backwards compatibility.

Testing in progress locally of the "local-chain" test against the same revisions as https://github.com/Agoric/testnet-load-generator/pull/71, as well as the current master of agoric-sdk: `12e61941`. Testing of the "testnet" version against the same agoric-sdk master revision is passing, allowing a safe merge without breaking agoric-sdk's CI.

Testing against the IST rename branch is currently failing with the solo trying to use `urun` instead of `uist` for gas.

2022-05-13 01:31 UTC, mhofman commented
Older revisions with Zoe fee purse are failing. I need to decide how ugly of a patch I want to handle that case.

2022-05-13 04:34 UTC, michaelfig requested changes
Looks good, but I'd strongly encourage you to use `keyword` instead of `symbol`.

2022-05-13 04:34 UTC, michaelfig commented on loadgen/contract/agent-create-vault.js
> + * @typedef { Pick<import('../types').NatAssetKit, 'brand' | 'purse' | 'displayInfo' | 'symbol'>} AssetKit
Technically, this is not a `symbol`, it's a Zoe `keyword`.  Unfortunately, this change has further repercussions below.

```suggestion
 * @typedef { Pick<import('../types').NatAssetKit, 'brand' | 'purse' | 'displayInfo' | 'keyword'>} AssetKit
```

2022-05-13 04:38 UTC, mhofman commented
> Looks good, but I'd strongly encourage you to use `keyword` instead of `symbol`.

I went by the nomenclature @dckc seem to have adopted in his PR. I did however just switch to a "keyword" name for vaults. Currently the keyword for those is still `RUN` which is obviously wrong, so making this PR draft until that gets settled.

2022-07-09 01:31 UTC, mhofman commented
Rebased PR on latest main, and update to use the `Minted` keyword for vaults according to https://github.com/Agoric/agoric-sdk/pull/5585. However that PR does not currently incorporate https://github.com/Agoric/agoric-sdk/pull/5332 which this was originally based against, so right now it'll not work (I've verified that this PR still runs correctly against the `5328-IST-boot`  branch if the vault keyword is forced to `RUN` in the vault task agent).

2022-07-26 21:51 UTC, turadg approved these changes
[Passed](https://github.com/Agoric/agoric-sdk/actions/runs/2742246120) against the last https://github.com/Agoric/agoric-sdk/pull/5585. Changes to that branch since then have been irrelevant tweaks (docs, types, methods that aren't used here.)

2022-07-26 22:35 UTC, merged